<a href="https://colab.research.google.com/github/kaushal4445/GEN_AI-TRAINING-CGC-UNIVERSITY/blob/main/LEARNING_PYTHON/GEN_AI_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n = np.array([1, 2, 3,4, 5, 6,7,8,9])
print(np.sum(n))
print(np.size(n))
print(np.max(n))
print(np.min(n))
print(np.mean(n))
print(np.median(n))
print(np.mode(n))

45
9
9
1
5.0
5.0

AttributeError: module 'numpy' has no attribute 'mode'

8th interview question

--> mean and median are  used to fill blank value in ML

--> axis  = 0, axis = 1 is used to calculate vertically
and horitzontally

and axis = 1 is mostly used in ML for drop dependent
variable/target variable for ML training purpose

Pandas is used for perform opereation on dataset

There are two types:

1.Series (1-D)

2.DataFrame(2-D)

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series()
print(s1)
s2 = np.array([1, 2,3, 4, 5])
s3 = pd.Series(s2)
print(s3)
s4 = pd.Series([11, 22, 33, 44])
print(s4)

Series([], dtype: object)
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    11
1    22
2    33
3    44
dtype: int64

Customize indexing are very importnat in ML

In [ ]:
s5 = pd.Series(["aman", "chaman", "sonu", "monu" ] , index = ["A", "B", "C", "D"])
print(s5)

A      aman
B    chaman
C      sonu
D      monu
dtype: object

Shape and dtype are important for ML

In [ ]:
s6 = pd.Series([10, 20, 30, 40, 50])

print(s6.index)
print(s6.shape)  # for dimension
print(s6.size)
print(s6.values)
print(s6.dtype) # type of data ML

RangeIndex(start=0, stop=5, step=1)
(5,)
5
[10 20 30 40 50]
int64

In [ ]:
data =[ [1, "david", "developer", 23000, "noida"],
       [2, "pitter", "programmer", 45000, "delhi"],
        [3, "kumar", "hr", 32000, "banglore"],
        [4, "Sahil", "trainee", 16000, "Chennai"],
        [5, "hari", "manager", 50000, "pune"]
]
df = pd.DataFrame(data, columns=["id", "Name", "Post", "Salary", "City"])
df

   id    Name        Post  Salary      City
0   1   david   developer   23000     noida
1   2  pitter  programmer   45000     delhi
2   3   kumar          hr   32000  banglore
3   4   Sahil     trainee   16000   Chennai
4   5    hari     manager   50000      pune

2nd Ways 2D Dataset

In [ ]:
emp = {
    "id" : [1, 2, 3, 4,5],
    "name" :["ram", "shyam", "nikhil", "david", "pitter"],
    "post" : ["developer", "programmer", "hr", "trainee", "manager"],
    "salary" : [23000, 45000, 32000, 16000, 50000],
    "city" :["noida", "delhi", "banglore", "chennai", "pune"]
}
df2 = pd.DataFrame(emp)
df2

   id    name        post  salary      city
0   1     ram   developer   23000     noida
1   2   shyam  programmer   45000     delhi
2   3  nikhil          hr   32000  banglore
3   4   david     trainee   16000   chennai
4   5  pitter     manager   50000      pune

In [ ]:
# print(df2["name"])
# print(df2["post"])
# print(df2.head(2)) # get top 2
# print(df2.tail(2))# get tail 2
# print(df2[df2["salary"] > 20000]) # whose salary greater than 20000

print(df2[(df2["salary"] >= 25000) & (df2["salary"] <= 35000)]) # salary b/w 35000 to 25000

   id    name post  salary      city
2   3  nikhil   hr   32000  banglore

In [ ]:
print(df2["salary"].max())
print(df2["salary"].min())

50000
16000

In [ ]:
print(max(["salary"]))

salary

In [ ]:
print(df2[["name", "post", "salary"]])

     name        post  salary
0     ram   developer   23000
1   shyam  programmer   45000
2  nikhil          hr   32000
3   david     trainee   16000
4  pitter     manager   50000

In [ ]:
df2["age"]  = [23,  25, 30, 32,22]
df2

   id    name        post  salary      city  age
0   1     ram   developer   23000     noida   23
1   2   shyam  programmer   45000     delhi   25
2   3  nikhil          hr   32000  banglore   30
3   4   david     trainee   16000   chennai   32
4   5  pitter     manager   50000      pune   22

In [ ]:
import pandas as pd

data = {
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": [
        "Rahul", "Priya", "Aman", "Neha", "Karan",
        "Simran", "Arjun", "Pooja", "Rohan", "Anjali"
    ],
    "post": [
        "Developer", "Designer", "Manager", "HR", "Developer",
        "Tester", "Developer", "Accountant", "Manager", "Designer"
    ],
    "salary": [
        55000, 48000, 75000, 45000, 62000,
        50000, 68000, 52000, 82000, 58000
    ],
    "city": [
        "Delhi", "Mumbai", "Chandigarh", "Mohali", "Bangalore",
        "Pune", "Hyderabad", "Jaipur", "Gurgaon", "Chennai"
    ],
    "age": [24, 26, 32, 27, 29, 25, 30, 28, 35, 31]
}

df = pd.DataFrame(data)

print(df)

   id    name        post  salary        city  age
0   1   Rahul   Developer   55000       Delhi   24
1   2   Priya    Designer   48000      Mumbai   26
2   3    Aman     Manager   75000  Chandigarh   32
3   4    Neha          HR   45000      Mohali   27
4   5   Karan   Developer   62000   Bangalore   29
5   6  Simran      Tester   50000        Pune   25
6   7   Arjun   Developer   68000   Hyderabad   30
7   8   Pooja  Accountant   52000      Jaipur   28
8   9   Rohan     Manager   82000     Gurgaon   35
9  10  Anjali    Designer   58000     Chennai   31

1.add columns bonus salary >= 40000

2. ---------- hra salary 10 %

3.------------da 5%

4.------------calculate Gross Salary ?

5.------------calculate Net Slary

In [ ]:
df["Bonus"] = np.where(df["salary"] >= 40000,df["salary"]* 0.05, 0)
df["HRA"] = df["salary"] * 0.10
df["DA"] = df["salary"] * 0.05
df["Gross Salary"] = df["salary"] + df["HRA"] + df["DA"]
df["Net Salary"] = df["Gross Salary"] - df["salary"]

In [ ]:
df

,id,name,post,salary,city,age,HRA,DA,Gross Salary,Net Salary,Bonus
0,1,Rahul,Developer,55000,Delhi,24,5500.0,2750.0,63250.0,8250.0,2750.0
1,2,Priya,Designer,48000,Mumbai,26,4800.0,2400.0,55200.0,7200.0,2400.0
2,3,Aman,Manager,75000,Chandigarh,32,7500.0,3750.0,86250.0,11250.0,3750.0
3,4,Neha,HR,45000,Mohali,27,4500.0,2250.0,51750.0,6750.0,2250.0
4,5,Karan,Developer,62000,Bangalore,29,6200.0,3100.0,71300.0,9300.0,3100.0
5,6,Simran,Tester,50000,Pune,25,5000.0,2500.0,57500.0,7500.0,2500.0
6,7,Arjun,Developer,68000,Hyderabad,30,6800.0,3400.0,78200.0,10200.0,3400.0
7,8,Pooja,Accountant,52000,Jaipur,28,5200.0,2600.0,59800.0,7800.0,2600.0
8,9,Rohan,Manager,82000,Gurgaon,35,8200.0,4100.0,94300.0,12300.0,4100.0
9,10,Anjali,Designer,58000,Chennai,31,5800.0,2900.0,66700.0,8700.0,2900.0

In [ ]:
df

,id,name,post,salary,city,age,HRA,DA,Gross Salary,Net Salary,Bonus
0,1,Rahul,Developer,55000,Delhi,24,5500.0,2750.0,63250.0,8250.0,2750.0
1,2,Priya,Designer,48000,Mumbai,26,4800.0,2400.0,55200.0,7200.0,2400.0
2,3,Aman,Manager,75000,Chandigarh,32,7500.0,3750.0,86250.0,11250.0,3750.0
3,4,Neha,HR,45000,Mohali,27,4500.0,2250.0,51750.0,6750.0,2250.0
4,5,Karan,Developer,62000,Bangalore,29,6200.0,3100.0,71300.0,9300.0,3100.0
5,6,Simran,Tester,50000,Pune,25,5000.0,2500.0,57500.0,7500.0,2500.0
6,7,Arjun,Developer,68000,Hyderabad,30,6800.0,3400.0,78200.0,10200.0,3400.0
7,8,Pooja,Accountant,52000,Jaipur,28,5200.0,2600.0,59800.0,7800.0,2600.0
8,9,Rohan,Manager,82000,Gurgaon,35,8200.0,4100.0,94300.0,12300.0,4100.0
9,10,Anjali,Designer,58000,Chennai,31,5800.0,2900.0,66700.0,8700.0,2900.0

give data Product ID, name, price, quantity, total price

0.add  column total price

1.add column discount if total_price 5000 then 10%

2. --------- free delivery if total _price total price 2000 free delivery

3.------ gst apply on total_price  with 8%

In [ ]:
import pandas as pd

data = {
    "Product ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Laptop", "Mouse", "Keyboard", "Monitor", "Headphones",
        "Webcam", "Printer", "USB Cable", "Hard Drive", "SSD"
    ],
    "Price": [55000, 800, 1500, 12000, 2500, 3500, 15000, 500, 6000, 7000],
    "Quantity": [2, 5, 3, 2, 4, 2, 1, 6, 3, 2]
}

df = pd.DataFrame(data)

# Calculate Total Price
df["Total Price"] = df["Price"] * df["Quantity"]

print(df)

   Product ID        Name  Price  Quantity  Total Price
0         101      Laptop  55000         2       110000
1         102       Mouse    800         5         4000
2         103    Keyboard   1500         3         4500
3         104     Monitor  12000         2        24000
4         105  Headphones   2500         4        10000
5         106      Webcam   3500         2         7000
6         107     Printer  15000         1        15000
7         108   USB Cable    500         6         3000
8         109  Hard Drive   6000         3        18000
9         110         SSD   7000         2        14000

In [ ]:
df["Discout"] = np.where(df["Total Price"] >= 5000, df["Total Price"] * 0.10, 0)
df["Free Delivery"] = np.where(df["Total Price"] >= 2000, "Free Delivery", "Not Free delivery")
df["GST"] = df["Total Price"] * 0.08

In [ ]:

df

,Product ID,Name,Price,Quantity,Total Price,Discout,Free Delivery,GST
0,101,Laptop,55000,2,110000,11000.0,Free Delivery,8800.0
1,102,Mouse,800,5,4000,0.0,Free Delivery,320.0
2,103,Keyboard,1500,3,4500,0.0,Free Delivery,360.0
3,104,Monitor,12000,2,24000,2400.0,Free Delivery,1920.0
4,105,Headphones,2500,4,10000,1000.0,Free Delivery,800.0
5,106,Webcam,3500,2,7000,700.0,Free Delivery,560.0
6,107,Printer,15000,1,15000,1500.0,Free Delivery,1200.0
7,108,USB Cable,500,6,3000,0.0,Free Delivery,240.0
8,109,Hard Drive,6000,3,18000,1800.0,Free Delivery,1440.0
9,110,SSD,7000,2,14000,1400.0,Free Delivery,1120.0